// Code generated by "stringer -type=TokenType -trimprefix=Token"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenError-0]
	_ = x[TokenEOF-1]
	_ = x[TokenLBrace-2]
	_ = x[TokenRBrace-3]
	_ = x[TokenLParen-4]
	_ = x[TokenRParen-5]
	_ = x[TokenLBracket-6]
	_ = x[TokenRBracket-7]
	_ = x[TokenColon-8]
	_ = x[TokenComma-9]
	_ = x[TokenDot-10]
	_ = x[TokenNewline-11]
	_ = x[TokenPipe-12]
	_ = x[TokenHash-13]
	_ = x[TokenLAngle-14]
	_ = x[TokenRAngle-15]
	_ = x[TokenEquals-16]
	_ = x[TokenSemicolon-17]
	_ = x[TokenPlus-18]
	_ = x[TokenMinus-19]
	_ = x[TokenTilde-20]
	_ = x[TokenStartUML-21]
	_ = x[TokenEndUML-22]
	_ = x[TokenClass-23]
	_ = x[TokenInterface-24]
	_ = x[TokenEnum-25]
	_ = x[TokenAbstract-26]
	_ = x[TokenExtends-27]
	_ = x[TokenImplements-28]
	_ = x[TokenPackage-29]
	_ = x[TokenNamespace-30]
	_ = x[TokenAs-31]
	_ = x[TokenStatic-32]
	_ = x[TokenField-33]
	_ = x[TokenMethod-34]
	_ = x[TokenParticipant-35]
	_ = x[TokenActor-36]
	_ = x[TokenBoundary-37]
	_ = x[TokenControl-38]
	_ = x[TokenEntity-39]
	_ = x[TokenDatabase-40]
	_ = x[TokenCollections-41]
	_ = x[TokenQueue-42]
	_ = x[TokenActivate-43]
	_ = x[TokenDeactivate-44]
	_ = x[TokenReturn-45]
	_ = x[TokenAlt-46]
	_ = x[TokenElse-47]
	_ = x[TokenEnd-48]
	_ = x[TokenLoop-49]
	_ = x[TokenGroup-50]
	_ = x[TokenNote-51]
	_ = x[TokenOf-52]
	_ = x[TokenOver-53]
	_ = x[TokenLeft-54]
	_ = x[TokenRight-55]
	_ = x[TokenArrow-56]
	_ = x[TokenSkinparam-57]
	_ = x[TokenHide-58]
	_ = x[TokenShow-59]
	_ = x[TokenTitle-60]
	_ = x[TokenHeader-61]
	_ = x[TokenFooter-62]
	_ = x[TokenIdent-63]
	_ = x[TokenString-64]
	_ = x[TokenNumber-65]
	_ = x[TokenLineComment-66]
	_ = x[TokenBlockComment-67]
}

const _TokenType_name = "ErrorEOFLBraceRBraceLParenRParenLBracketRBracketColonCommaDotNewlinePipeHashLAngleRAngleEqualsSemicolonPlusMinusTildeStartUMLEndUMLClassInterfaceEnumAbstractExtendsImplementsPackageNamespaceAsStaticFieldMethodParticipantActorBoundaryControlEntityDatabaseCollectionsQueueActivateDeactivateReturnAltElseEndLoopGroupNoteOfOverLeftRightArrowSkinparamHideShowTitleHeaderFooterIdentStringNumberLineCommentBlockComment"

var _TokenType_index = [...]uint16{0, 5, 8, 14, 20, 26, 32, 40, 48, 53, 58, 61, 68, 72, 76, 82, 88, 94, 103, 107, 112, 117, 125, 131, 136, 145, 149, 157, 164, 174, 181, 190, 192, 198, 203, 209, 220, 225, 233, 240, 246, 254, 265, 270, 278, 288, 294, 297, 301, 304, 308, 313, 317, 319, 323, 327, 332, 337, 346, 350, 354, 359, 365, 371, 376, 382, 388, 399, 411}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
